title: Flyte
description: Flyte enables production-grade orchestration for machine learning workflows and data processing created to accelerate local workflows to production.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.flyte.org" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag

#Links within the site
documentation: "https://docs.flyte.org/"
getstarted: "https://docs.flyte.org/en/latest/getting_started/index.html"
contribute: "https://docs.flyte.org/en/latest/community/contribute.html"
learnmore: "https://docs.flyte.org/en/latest/index.html"
email_list: "https://groups.google.com/u/0/a/flyte.org/g/users"
blog: "https://blog.flyte.org/"
github: "https://github.com/flyteorg/flyte"
twitter: "https://twitter.com/flyteorg"
stackoverflow: "https://stackoverflow.com/questions/tagged/flyte"
slack: "https://slack.flyte.org"
discussions: "https://github.com/flyteorg/flyte/discussions"
youtube: "https://www.youtube.com/channel/UCNduEoLOToNo3nFVly-vUTQ/playlists"
community_syncup: "https://www.addevent.com/calendar/kE355955"
office_hour_morning: "https://www.addevent.com/event/zF10349020/"
office_hour_evening: "https://www.addevent.com/event/dQ10349168/"
newsletter: "https://www.getrevue.co/profile/flytedo"
concepts: "https://docs.flyte.org/en/latest/concepts/basics.html"
userguide: "https://docs.flyte.org/projects/cookbook/en/latest/index.html"
tutorials: "https://docs.flyte.org/projects/cookbook/en/latest/tutorials.html"
apidocs: "https://docs.flyte.org/en/latest/reference/index.html"
deployment_guide: "https://docs.flyte.org/en/latest/deployment/index.html"
roadmap: "https://github.com/orgs/flyteorg/projects/3"
status: "https://status.flyte.org/"
deployments: "https://github.com/flyteorg/flyte#%EF%B8%8F-current-deployments--contributors"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
