title: Flyte 
description: Flyte enables production-grade orchestration for machine learning workflows and data processing created to accelerate local workflows to production.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.flyte.org" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag

#Links within the site
documentation: "https://lyft.github.io/flyte/"
getstarted: "https://lyft.github.io/flyte/user/getting_started/index.html"
contribute: "https://lyft.github.io/flyte/contributor/index.html"
learnmore: "https://lyft.github.io/flyte/"
email: "https://groups.google.com/d/forum/flyte-discuss"
blog: "https://medium.com/flyte-org"
github: "https://github.com/lyft/flyte"
community: "https://flyte-org.slack.com"
twitter: "https://twitter.com/flyteorg"
stackoverflow: "https://stackoverflow.com/questions/tagged/flyte"

destination: _site

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
